### ISSUE TITLE
Super healing potion filtered

### ISSUE THREAD

**Issue by raine** [Darain2/PoD-lootfilter#2]
Hi there,

Is it intentional that super healing potion (hp5) is filtered but greater healing potion (hp4) is not?

Think it's because of this line: https://github.com/Darain2/PoD-lootfilter/blob/main/Darain%20Shungite.filter#L746

**Comment by Darain2** [comment]
Apologies for the late reply. I didn't get notified of this, I'm still an amateur when it comes to github.
I must have uploaded an old version where I was hacking together the filter during the reset and didn't change the filter back to what it was supposed to.

Fixed it, hope the filter works good, and please let me know if you have any issues or suggestions.
